### ISSUE TITLE
White block on top screen when activating modal slider

### ISSUE THREAD

**Issue by anniinakovalainen** [GispoCoding/tarmo#109]
A white block appears on top screen when clicking objects on map and activating modal slider. I cannot find any bug in CSS or HTML that could solve the issue.

![image](https://user-images.githubusercontent.com/51991990/158204759-77ce932d-1c8a-4825-bf8d-f316c097a4e4.png)

**Comment by Joonalai** [comment]
I can't reproduce the issue. I tried firefox and chrome on PC and Opera on Android. Which device and browser are you using?

**Comment by anniinakovalainen** [comment]
Hah, I think it resolved itself after merging the styling branch. I cannot reproduce it anymore. Good!
