### ISSUE TITLE
Change the "snapping distance" of the cursor

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/tarmo#134]
Currently the cursor needs to be quite accurately on top of the point symbol in order to change the cursor active (allowing to click the feature to see all attribute information). Figure out if this "radius" / "distance" can be increased to that the cursor would "snap" to features further away.

Take a closer look on whether MapLibre supports adjusting this sensitivity parameter e.g. by setting a buffer radius.

**Comment by Rikuoja** [comment]
I guess this means increasing the symbol.

We should try making the lines thicker at closer zooms. It is easy to make a line thickness depend on zoom level.

**Comment by Rikuoja** [comment]
". Viivamaisissa kohteissa tarttumispinta-ala on aika kapea, siihen on hankala osua kun haluaa klikata kohdetta ja saada lisätietoa."

**Comment by Rikuoja** [comment]
Increased the line width when zoomed. Any better now?

**Comment by SannaJokela** [comment]
Better thank you!
