### ISSUE TITLE
Add database tables for storing data generated by tarmo admins

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/tarmo#135]
There are some pieces of information we cannot fetch directly from any datasource. Rather, admin of the tarmo application should make decisions regarding:

- [x] visibility field value for each object in tamperewfs_luonnonmuistomerkit, tamperewfs_luontorastit, tamperewfs_luontopolkureitit, museovirastoarcrest_rkykohteet and museovirastoarcrest_muinaisjaannokset tables
- [x] season field value for each object in lipas_pisteet and lipas_viivat tables.

After the decisions are made, the generated data needs to be stored somewhere. In other words, adding more database tables is needed.

**Comment by pavetsu14** [comment]
In later phases adding more this kind of data (data created for this application which cannot be fetched directly from any datasource) might become topical.

- A field storing image urls from each object in kooste schema is one such possibility
- Another possibility is adding a field into which tarmo admin could add some additional information regarding to an object in kooste schema (inner notes, not visible to the user)

**Comment by SannaJokela** [comment]
@pavetsu14 visibility field propably to OSM-parking is needed also - this was requested by the client (some of the parking places are not publicly available)

**Comment by SannaJokela** [comment]
@pavetsu14 season is not necessary information at all. It was requested that the skiing routes etc. are always visible (there are people who love to check the routes before hand and design their winter activities). But winter sports could be arranged with the filter-tool to be  "at the bottom" of the list when it is summer. I'll add another issue on this.

**Comment by pavetsu14** [comment]
We have not intended to show season value for the users. It is just stored in the database in order to make it possible t show only summer POIs in summer but if this is not desired, we can surely alter it show that the order changes. Either way, the knowledge about season each point is related to, is needed.

**Comment by SannaJokela** [comment]
Or just to have it done in the UI/frontend: if category is skiing or skating ==> icon goes to last when date is 1.5.

**Comment by SannaJokela** [comment]
I think this issue has become obsolete, closing this.
