### ISSUE TITLE
Add icons to second modal slider page

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/tarmo#137]
See second and fourth slide of [Aineistot ja suodattimet file](https://docs.google.com/spreadsheets/d/1XwmJJgNAHxdRHIwVP_5ptSLTovXTej90jG1tt5Jjac8/edit?usp=sharing). From there you can find the attribute fields to be shown to the user via icons. Add each piece of information to be represented as icon to the second modal slider page if the corresponding attribute field (of type boolean) is True.

Note that the icons have been already downloaded by @anniinakovalainen 

Question: do we want to create icons also for situations when boolean information is available, but its value is False or do we just want to not show the icon in such cases? The downside of not showing the icon is that by acting that way we lose information (as no information was available at all).

> Current decision: Let's treat False values as NULLs

**Comment by SannaJokela** [comment]
Check this [list](https://docs.google.com/spreadsheets/d/1XwmJJgNAHxdRHIwVP_5ptSLTovXTej90jG1tt5Jjac8/edit?usp=sharing)

**Comment by SannaJokela** [comment]
Tuomas has done planning for this, when ready this can be closed.

**Comment by Rikuoja** [comment]
Done in #160
