### ISSUE TITLE
Add OSM data - entrepreneurs in recreation business & other tourism sites

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#141]
OSM POIs from e.g. 

### https://wiki.openstreetmap.org/wiki/Key:amenity

**Sustenance**
[cafe](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe)
[ice_cream](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dice_cream) Filter show only in summer time
[restaurant](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drestaurant) ? There are plenty of these, too much? Cafe and ice cream is enough?)

**Rental:**
<s>[bicycle_parking](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_parking)</s>
<s>[bicycle_repair_station](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_repair_station)</s>
[bicycle_rental](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_rental)
<s>[boat_rental](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dboat_rental) ==> includes canoe rentals, (no results)</s>
<s>[boat_sharing](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dboat_sharing) (no results)</s>
<s>[car_rental](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcar_rental) ? (No need)</s>
<s>[car_sharing](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcar_sharing) ? (no results)</s>

**Faclities**
[bbq](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbbq) (Filter: only public, to laavut, majat & ruokailu layer)
[bench](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench) -->to Laavut & Majat layer subcategory
shelter? --> to Laavut & Majat
<s>[dog_toilet](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddog_toilet)</s>
<s>[drinking_water](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddrinking_water) (Only one, no need?)</s>
<s>[shower](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dshower) (Only one, no need?)</s>
[toilets](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets) --> Laavut & Majat layer subcategory
[waste_basket](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_basket), [recycling](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling) (Filter: only public, both on same layer? Laavut & Majat layer subcategory?)
<s>[place_of_worship](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dplace_of_worship) (no need? enough when these are on basemap)</s>

### https://wiki.openstreetmap.org/wiki/Key:shop

Do we want to have shops, then there are these possibilities:
_No need for shops ?_

**General store, department store, mall**

[general](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dgeneral) 
[kiosk](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dkiosk)
[supermarket](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dsupermarket) ?

**Outdoors and sport, vehicles**

<s>[bicycle](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle)
[boat](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dboat)
[fishing](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dfishing)
[outdoor](https://wiki.openstreetmap.org/wiki/Tag:shop%3Doutdoor)
[ski](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dski) ==> should sometimes have also ski: rental tag</s>

### https://wiki.openstreetmap.org/wiki/Key:tourism

**"Open" tourism sites**

[information](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dinformation)--> added to Ulkoilureitit
[picnic_site](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dpicnic_site) --> there were lots, added to Laavut, majat
[viewpoint](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dviewpoint) to nähtävyydet layer
[wilderness_hut](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dwilderness_hut) --> only three varaustupa. If we want those, in majoitus layer?
<s>[travel_agency](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dtravel_agency)</s>
[museum] --> Nähtävyydet

**Do we want to have hotels/hostels/camping sites? If so here are some possibilities:**

<s>[camp_pitch](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcamp_pitch) (ei tuloksia)</s>
[camp_site](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcamp_site) --> to leirintä & majoitus layer
[caravan_site](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcaravan_site) --> to leirintä & majoitus layer
[chalet](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dchalet) --> to leirintä & majoitus layer
[guest_house](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dguest_house) --> to to leirintä & majoitus layer
[hostel](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dhostel) --> to leirintä & majoitus layer
[hotel](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dhotel) --> to leirintä & majoitus layer
[information](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dinformation) --> parking layer subcategory?
[motel](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dmotel) --> to leirintä & majoitus layer

### https://wiki.openstreetmap.org/wiki/Key:leisure
sauna

**Comment by joonaris** [comment]
laavut, majat & ruokailu tason jakaisin kahteen tasoon niin että laavut &majat omalla ja ruokailu taso omalla

**Comment by joonaris** [comment]
Lipas ruuanlaittopaikan siirtäisin tälle ruokailu tasolle

**Comment by joonaris** [comment]
Kategorisoinnissa voisi ottaa mallia retkikartasta:
![image](https://user-images.githubusercontent.com/104818918/169790196-ae37f4d8-82e6-47b8-8fa5-72e2ed85db11.png)
![image](https://user-images.githubusercontent.com/104818918/169790268-4c2f78ce-f052-42d7-a17f-f7bdf5c708b7.png)

**Comment by Rikuoja** [comment]
Some of this data is ways, some are points. Ways to handle the difference:

1) currently, only points are clustered in the all_points layer, areas are only visible when you zoom in close
2) also cluster areas by e.g. their centroids, add those to separate layer or add those to all_points layer??

**Comment by Rikuoja** [comment]
Did 2)
