### ISSUE TITLE
Add duplicate routes from Tampere WFS to "unvisible"

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#153]
Check what routes are already existing in Lipas and tap the unvisible. 

Example: Niihamaa has douple routes

![image](https://user-images.githubusercontent.com/23258285/160995413-b4fede43-92d0-494e-abd4-15f84f2957e7.png)

**Comment by Rikuoja** [comment]
Just removed the WFS routes. All the routes we need should be in Lipas.
