### ISSUE TITLE
Own icon for Muinaisjäännös

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#159]
There are a lot of POIs in Muinaisjäännös-category, so it might be good to sort them separately.

- [x] own icon
- [x] add icon to filtertool
- [x] add own category to database

**Comment by Rikuoja** [comment]
Added points to new "Muinaisjäännökset" category in the database. Didn't find an icon (hannunvaakuna? some ruins? etc.) yet, so @Kaemppi will have to do that part!

**Comment by SannaJokela** [comment]
@Kaemppi tää oli vissiin done, saatko suljettua issuen?
