### ISSUE TITLE
Import data from Museovirasto

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/tarmo#16]
Let's add Museovirasto to the list of used data sources. Let's fetch data about

- Muinaisjäännökset
- Rakennetun ympäristön kulttuuri- ja maisemakohteet
- something else?

Data can be fetched via ArcGIS Rest Servers with url http://kartta.nba.fi/arcgis/rest/services/WFS/MV_KulttuuriymparistoSuojellut/MapServer/ 

The municipalities should take a look at the features and identify which ones we want to show in the map service?

Tasks:

- [x] Create new tables to kooste schema where we can store this information (@pavetsu14)
- [ ] Create loader which populates the data into correct fields (@Rikuoja)

**Comment by SannaJokela** [comment]
@Rikuoja @pavetsu14 has this been solved? Riku did some systems for ArcGIS Rest servers, but is the data working correctly?

**Comment by pavetsu14** [comment]
@SannaJokela No; to my understanding this is under development. There are tables in the database but no loader yet to fill them with data.

**Comment by SannaJokela** [comment]
Data added to Tarmo
