### ISSUE TITLE
Import data from Syke

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/tarmo#17]
Let's add Syke to the list of used data sources. Let's fetch data about

- Natura-alueet SPA
- Natura-alueet SCI
- Natura-alueet SAC
- Valtion maiden luonnonsuojelualueet

Data can be fetched via ArcGIS Rest Servers with url
https://paikkatieto.ymparisto.fi/arcgis/rest/services/SYKE/SYKE_SuojellutAlueet/MapServer 

The municipalities should take a look at the features and identify which ones we want to show in the map service?

Tasks:
- [ ] Create new tables to kooste schema where we can store this information (@pavetsu14)
- [ ] Create loader which populates the data into correct fields (@Rikuoja)

**Comment by SannaJokela** [comment]
@anniinakovalainen was this fixed already?

**Comment by Rikuoja** [comment]
This is *not* a database issue.

This should *not* be added from the link described in the issue.

**Comment by SannaJokela** [comment]
@anniinakovalainen status on this? this was prioritized top

**Comment by anniinakovalainen** [comment]
@SannaJokela In progress, Maputnik is giving me a headache (json isn't working properly).

**Comment by anniinakovalainen** [comment]
@SannaJokela Turns out that the nature conservation areas are NOT in the MML background map. Therefore I cannot add them into the background map. The background map has "maasto_alue" and "maankaytto" layers, but not "suojelukohteet".

**Comment by anniinakovalainen** [comment]
The type ids that needs to be added are:
- Kansallispuisto 72202
- Luonnonpuisto 72201
- Muu luonnonsuojelualue 72200

**Comment by SannaJokela** [comment]
@anniinakovalainen So are they or are they not possible to add via NLS or do we need a separate layer?

**Comment by anniinakovalainen** [comment]
@SannaJokela We need a separate layer.

**Comment by Rikuoja** [comment]
I will add the tables in the schema at the same time as the arcgis importer. Will have to add metadata tables too anyway.

**Comment by SannaJokela** [comment]
Data added to Tarmo
