### ISSUE TITLE
Import data from Digitransit

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/tarmo#18]
Let's add Nysse to the list of used data sources. Let's fetch data about

- [ ] Public transport stops
- [ ] Routes ?
- [ ] Timetable info?

Must include at least the locations of public transport stops.

Get data via
https://digitransit.fi/en/developers/

**Comment by Rikuoja** [comment]
https://docs.mapbox.com/mapbox-gl-js/example/external-geojson/ plus https://docs.mapbox.com/mapbox-gl-js/example/live-geojson/
