### ISSUE TITLE
Import Luontomuistomerkit from Tampere interface

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/tarmo#20]
Let's fetch data about

- [ ] Luonnonmuistomerkit
- [ ] Luontopolut
- [ ] Luontopolkurastit
- something else?

Data can be fetched via WFS with url
https://geodata.tampere.fi/geoserver/ows?service=wfs&version=1.0.0&request=GetCapabilities

**Comment by SannaJokela** [comment]
There are some issues with the data, so I'll change the milestone to V2 if the data is fixed by then.

**Comment by Rikuoja** [comment]
Data contains a cryptic `MI_PRINX` id field, so let's use it for now.
