### ISSUE TITLE
Make some lipas tables to work

### ISSUE THREAD

**Issue by Joonalai** [GispoCoding/tarmo#25]
The initial mapping in lipas_loader does not work with following Lipas types:

| Table name                   | Lipas type name            |
|------------------------------|----------------------------|
| lipas.ulkoilumaja_hiihtomaja | Ulkoilumaja/hiihtomaja     |
| lipas.kavely_ulkoilureitti   | Kävelyreitti/ulkoilureitti |
| lipas.laavu_kota_kammi       | Laavu , kota tai kammi     |
| lipas.frisbeegolf_rata       | Frisbeegolfrata            |
| lipas.veneilyn_palvelupaikka | Veneilyn palvelupaikka     |

**Comment by pavetsu14** [comment]
@Rikuoja I changed the name of frisbeegolf_rata table to frisbeegolfrata so do not worry about it!
