### ISSUE TITLE
Harden the terraform configuration

### ISSUE THREAD

**Issue by Joonalai** [GispoCoding/tarmo#26]
Some examples:
- Move db to private subnet
- Use bastion host to access db

Useful links:
- Look some examples [here](https://www.metosin.fi/blog/terraform-ecs-example/)

**Comment by Rikuoja** [comment]
While at it, fix the conflict between lb security group and security group rule resources. Causes recreating/destroying resources between runs.

From https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule
> Terraform currently provides both a standalone Security Group Rule resource (a single ingress or egress rule), and a [Security Group resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group) with ingress and egress rules defined in-line. At this time you cannot use a Security Group with in-line rules in conjunction with any Security Group Rule resources. Doing so will cause a conflict of rule settings and will overwrite rules.

**Comment by Rikuoja** [comment]
Lambda needs vac connections:

https://www.maxivanov.io/deploy-aws-lambda-to-vpc-with-terraform/

**Comment by Rikuoja** [comment]
VPC and security group rules implemented. DB can only be accessed from the ec2 instance in the same VPC.
