### ISSUE TITLE
Load data from LIPAS periodically

### ISSUE THREAD

**Issue by Joonalai** [GispoCoding/tarmo#27]
Use [cloudwatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/RunLambdaSchedule.html) to accomplish this.

**Comment by SannaJokela** [comment]
Daily was requested.

**Comment by SannaJokela** [comment]
@Joonalai is it possible to activate this already, the client is waiting to see their newest corrections on the map...

**Comment by Joonalai** [comment]
@Rikuoja do you have time to implement this on AWS temporarily?

**Comment by SannaJokela** [comment]
It was decided in TARMO-team, that we could do this once a month in the development phase in developers computer

**Comment by SannaJokela** [comment]
@Rikuoja this was done I think?

**Comment by Rikuoja** [comment]
According to logs, this works on AWS now.
