### ISSUE TITLE
Mobile view is scewed

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#28]
Somehow the map shows a bit scewed in moblie phone views. Tested with Android. 

Edit: added screenshots
![Screenshot_20220202-074850_Chrome](https://user-images.githubusercontent.com/23258285/152100577-52429c82-3118-4f58-8bfc-831633380386.jpg)
![Screenshot_20220202-074911_Chrome](https://user-images.githubusercontent.com/23258285/152100583-0c692967-6011-40b7-b7c0-a6f4e3efa810.jpg)

**Comment by anniinakovalainen** [comment]
I cannot replicate the problem with iOS or android. Do you have a screenshot?

**Comment by Rikuoja** [comment]
This happens only in vertical mode on Android. In vertical mode, also the zoom buttons etc. are very small. Probably Maplibre interprets the Android phone viewport resolution somehow wrong.

When you turn the phone to horizontal, the shape is alright.

Probably this is an issue with MaplibreJS.

**Comment by mvaaltola** [comment]
Potential fix in 4217a84ab81e6aa909e73bac1177fe172a31d677
