### ISSUE TITLE
Render labels on top of other layers

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#31]
Render labels always on Top of all other layers, at least the routes and points. Now they are hiding behind the pointmass. 

<img width="394" alt="image" src="https://user-images.githubusercontent.com/23258285/150079653-afc3a9b8-58e1-4e20-8d53-9bd3aeed7239.png">

Blocked by #62.

**Comment by mvaaltola** [comment]
Possible, but requires a new style that renders only labels.

**Comment by SannaJokela** [comment]
@anniinakovalainen noticed that there are no labels at the moment... is this "functionality" somehow related to this?

**Comment by SannaJokela** [comment]
Duplicate with this? #124?

**Comment by mvaaltola** [comment]
Yes, seems to be a duplicate. Closing the other one
