### ISSUE TITLE
Add: Info pop-ups for layers

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#34]
- [ ] Pop-ups for vector datasets based on mockups. 
![infopopup](https://user-images.githubusercontent.com/23258285/150934580-fa37bcb5-5332-400a-b45d-b528e7ec98cb.png)

![infopopup2](https://user-images.githubusercontent.com/23258285/150934618-121a42be-faa9-43ef-8b15-f02b98312cfb.png)

![infopopup3](https://user-images.githubusercontent.com/23258285/150934631-d1a44095-ae4f-466a-9119-6dafe506d167.png)

**Comment by SannaJokela** [comment]
@anniinakovalainen styling for info-popups is needed. Shall we do a new task or is this ok?

**Comment by mvaaltola** [comment]
Done in #54, created new issue #61 for adding styles.
