### ISSUE TITLE
Clustering point-data

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#37]
- [ ] Cluster POIs with suitable zoomlayers

![clusteringpoints](https://user-images.githubusercontent.com/23258285/150935072-4ae59c43-929f-44d5-993d-33291394e410.png)

**Comment by Rikuoja** [comment]
https://docs.mapbox.com/mapbox-gl-js/example/cluster/

**Comment by SannaJokela** [comment]
Joona: idea using pgtile serv - clustering in database, front decides to show the cluster symbol by the zoom level.
