### ISSUE TITLE
Add filtering by Tarmo category

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#41]
Possible tarmo_categories for Lipas features:
- Hiihto
- Luistelu
- Uinti
- Vesillä ulkoilu
- Laavut, majat, ruokailu
- Ulkoilupaikat
- Ulkoiluaktiviteetit
- Pyöräily
- Ulkoilureitit

Rest of the possible tarmo_categories:
- Nähtävyydet
- Pysäköinti
- Tausta-aineistot (sisältää käytännössä luonnonsuojelualueet)

<img width="227" alt="image" src="https://user-images.githubusercontent.com/23258285/150937140-603a4420-322e-4fb3-a1a0-0f1d3810b202.png">

Tasks:

- [x] Add tarmo_category variable to each database table (@pavetsu14)
- [x] Add logic for populating tarmo_category field in lipas tables with correct value by utilizing jsonb lists in kooste.metadata table (@Rikuoja)
- [x] Create filter menu showing list of tarmo_categories (@Rikuoja)
- [x] Add functionality to tarmo_category filter menu (@Kaemppi)

**Note.** At this point it has been decides that one feature can go only into one category. But if it causes issues later on, we can check if the features can belong to one or several categories.

**Comment by Rikuoja** [comment]
This is a UI issue. The database contains all the objects already. Perhaps some classifications should be added in the database too?

**Comment by pavetsu14** [comment]
@Rikuoja Perhaps. Since we already have done an initial division of type codes to filterable classes, I maybe should add a table into kooste schema containing jsonb lists of type codes belonging to each filter class?

**Comment by pavetsu14** [comment]
QUESTION.

We now have exclusive classification principle meaning that if particular lipas point belongs to a filtering category, e.g. Vesillä ulkoilu, it does not belong to any other filtering category. Though kalastusalue/-paikka could be seen also as Ulkoiluaktiviteetit?

**Comment by SannaJokela** [comment]
@pavetsu14 I think it would be good to have category so that the features can belong to several categories. Is this a problem in the database-level?

**Comment by pavetsu14** [comment]
@SannaJokela Allowing features to belong to multiple categories at the same time is not necessarily a problem but in order to make sure that everything works as expected, it might be better to start with simple division approach (i.e. each feature belongs to one filtering category). It might even be that the users prefer this "simple" approach. I think this could be something where we need complexity if it gets requested.

Regarding to new filtering categories -> I will deploy the changes into database model!

**Comment by anniinakovalainen** [comment]
This issue is closely related to the issue #120. Placeholders and styling for the filtering component has been done. So far looks like this: 
![image](https://user-images.githubusercontent.com/51991990/159679571-f7ecb843-451f-4ec5-8c6c-f75f0288c2f8.png)
