### ISSUE TITLE
Import data from OpenStreetMap

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/tarmo#51]
Let's fetch data about

- [ ] parking places

Let's collect minimum amount of attribute data; possibly just osm-id.

**Comment by Rikuoja** [comment]
Non-private: https://overpass-turbo.eu/s/1g7S

**Comment by Rikuoja** [comment]
10 kilometers around center point: https://overpass-turbo.eu/s/1g9p

**Comment by Rikuoja** [comment]
Done.
