### ISSUE TITLE
Testing with end users

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#56]
In May a test for end users in the field.

- around 100 users
- name competition?
- 2 weeks time for testing?
- how to collect feedback? Field observations?

**Comment by SannaJokela** [comment]
Idea:

Would it be easy to have a new test-button in the UI that directs to google forms? 

Some simple questions, like: did you find the information you needed (scale 1-4), did the service cover all needed information? etc.

**Comment by SannaJokela** [comment]
Solution:

Ekokumppanit will send out a media announcement in late April and gathers the test audience. The testers will be sent a short instruction and link to Tarmo. Then they have 2 weeks time to test. The questionnaire is either within Tarmo or in the email (which is easier). The ideas are then prioritized based on  criteria like:

1.  have to fix
2.  good idea, let's fix this in next phases 
3.  not possible / not a good idea

**Comment by SannaJokela** [comment]
Testdate: 20.5.-5.6. around 200 testers. Ekokumppanit sends the message & questionnaire.

**Comment by Rikuoja** [comment]
Done!
