### ISSUE TITLE
Add icon library

### ISSUE THREAD

**Issue by anniinakovalainen** [GispoCoding/tarmo#83]
Find or create an icon library which has vast selection of sport icons.

**Comment by anniinakovalainen** [comment]
Suggestion for icon library
- https://icons8.com/icons
- Style as iOS glyphs
- License: can be used for free as long as Icons8 is mentioned and linked in the app

**Comment by SannaJokela** [comment]
@anniinakovalainen is this solved?

**Comment by anniinakovalainen** [comment]
@SannaJokela I changed the issue to "add icon library", because utilizing is related to so many other issues. Now this is solved!
