### ISSUE TITLE
Change popups into bottom screen modal slider

### ISSUE THREAD

**Issue by anniinakovalainen** [GispoCoding/tarmo#89]
![image](https://user-images.githubusercontent.com/51991990/155689193-757b19bb-17b4-47d9-9321-5ce396180965.png)
![image](https://user-images.githubusercontent.com/51991990/155689217-7843ac0c-d876-429e-8d68-95620e74f97d.png)
![image](https://user-images.githubusercontent.com/51991990/155689237-8dc0a355-906c-45e0-be12-d0f93cbe022c.png)

**Comment by SannaJokela** [comment]
@anniinakovalainen add more info

**Comment by Joonalai** [comment]
@Rikuoja I started working on this last night. I will push some (possibly draft) PR later on.
