### ISSUE TITLE
Change top right menu custom buttons into radio buttons

### ISSUE THREAD

**Issue by anniinakovalainen** [GispoCoding/tarmo#90]
Only one button of the top right menu should be open at a time. If one is clicked while other is open, then the other closes.

**Comment by SannaJokela** [comment]
@mvaaltola is this V1 thing or can I change the milestone?

**Comment by mvaaltola** [comment]
Best to leave this in V1, I'll see if I can do this tomorrow.

**Comment by SannaJokela** [comment]
@mvaaltola status on this?
