### ISSUE TITLE
Add content for InfoButton items

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#98]
![image](https://user-images.githubusercontent.com/23258285/156360670-e57393e6-d633-4d34-a7db-6f1fd922d573.png)

Needs comments from Tampere city region:

What kind of info wanted? ==> suggestion in the comments

**Comment by anniinakovalainen** [comment]
Palvelun tiedot -kohtaan tulisi laittaa Tampereen retkeilykarttapalvelun tuottajat. Lisensseihin tulisi laittaa palvelun lisenssi (MIT) sekä maininta ikoneista. Tietosuojaan tietoa siitä, tallentaako sovellus jotain käyttäjästään jne. Palaute on ehkä vähän turha, mutta ite ajattelin siinä lähinnä sitä että jos haluaa antaa palautetta sovelluksesta, mutta sen voisi ehkä laittaa tuonne "palvelun tiedot"-kohtaankin.

**Comment by SannaJokela** [comment]
**Palvelun tiedot:**

Tampereen kaupunkiseudun ulkoilu- ja retkeilykarttapalvelua kehitetään yhteistyössä Ekokumppanit Oy:n, Gispo Oy:n ja Tampereen kaupunkiseudun kuntien kanssa. Palvelu on beta-vaiheessa vuonna 2022 ja sitä testataan ja kehitetään eteenpäin jatkuvasti. Tuotantoon palvelun on tarkoitus siirtyä syksyllä 2022. 

Toteutus tehdään perustuen avoimiin datalähteisiin ja avoimen lähdekoodin komponentteihin. Lähdekoodi on julkaistu osoitteessa: https://github.com/GispoCoding/tarmo 

Lisätietoa palvelun kehityksestä: Petri Mäkelä, Ekokumppanit Oy (petri.makela@tampere.fi).

**Lisenssit**

Palvelun lähdekoodin lisenssi on MIT-lisenssi. 

Aineistojen lisenssit riippuvat datalähteestä. Palvelussa haetaan suoraan tiedot seuraavista avoimista rajapinnoista:

[_Tampereen kaupungin WFS-rajapinta_](https://geodata.tampere.fi/geoserver/web/)
Avoin data (lisenssi?)
Luontopolkurastit

_[Jyväskylän yliopisto, Lipas Liikuntapaikat.fi](https://www.lipas.fi/etusivu)_

Lipas-tietokannan käyttöehdot noudattavat avoimen datan [CC Nimeä 4.0 ](https://creativecommons.org/licenses/by/4.0/deed.fi)Kansainvälinen -lisenssiä.

Tiedot haetaan Lipas-tietokannasta päivittäin palveluun. Kaikkia Lipas-kohteita ei haeta vaan palveluun on valittu ulkoliikuntaan ja retkeilyyn soveltuvat reitit ja kohteet. 
 
_[Museovirasto](https://www.museovirasto.fi/fi/palvelut-ja-ohjeet/tietojarjestelmat/kulttuuriympariston-tietojarjestelmat/kulttuuriympaeristoen-paikkatietoaineistot)_
Museoviraston paikkatiedot on julkaistu [Creative Commons CC By 4.0 -lisenssillä](https://creativecommons.fi/lisenssit/).

Museovirastolta hyödynnetään muinaisjäännöksiä ja RKY-tietoja (valtakunnallisesti merkittävät rakennetut kulttuuriympäristöt). 

_[Maanmittauslaitos](https://www.maanmittauslaitos.fi/tietoa-maanmittauslaitoksesta/teemat/tutustu-rajapintapalveluiden-kayttoon/rajapintojen-kautta)_
Maanmittauslaitoksen avoimen tietoaineiston Nimeä CC 4.0 -lisenssi
Tiedoista hyödynnetään Maastokarttaa, Ilmakuvia sekä Taustakarttasarjaa, jonka vektoritiiliin perustuva visualisointi on luotu tähän palveluun erikseen Gispo Oy:n toimesta. 

 **_[OpenStreetMap](https://www.openstreetmap.org/)_**
Kiitos OpenstreetMap-yhteisölle!
OpenStreetMap[®](https://www.openstreetmap.org/copyright#trademarks) on avointa dataa, jonka [OpenStreetMap Foundation](https://osmfoundation.org/) (OSMF) on lisensoinut [Open Data Commons Open Database -lisenssillä](https://opendatacommons.org/licenses/odbl/) (ODbL).

OpenStreetMapin karttoja ja tietoja voi kopioida, levittää, välittää ja mukauttaa, kunhan OpenStreetMap ja sen tekijät mainitaan. Jos karttoja tai tietoja muutetaan tai kehitetään, niitä saa levittää vain samalla lisenssillä. [Lakitekstissä](https://opendatacommons.org/licenses/odbl/1.0/) mainitaan levittäjän oikeudet ja velvollisuudet.

Dokumentaatio on lisensoitu [Creative Commons Nimeä-JaaSamoin 2.0](https://creativecommons.org/licenses/by-sa/2.0/deed.fi) -lisenssillä (CC-BY-SA 2.0).

OpenStreetMapista palveluun tuodaan parkkipaikat sekä muita palvelutietoja.
