### ISSUE TITLE
Styling for routes and points

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#99]
**Need:**

- Icons and styling for vector layers from PostGIS (kooste schema) plus external layers (public transport)
- #41 needs to be fixed first

**Question 1:**

Now all points and routes are equal, do we want to classify routes and point on the map or only on the selection? (Currently, parking, bus, train and tram are *not* equal):

- Different colours/linetypes for different routes, classified by? ==> was decided on 23.3.2022 that lines are all same colour, filtering shows the different types better. 
- Different colours or point symbols for different points (if needed, the filtering tool might do the trick) ==> was decided on 23.3.2022 that the point color is the same for most points, only public transport and parking are different colour. 
- Different colours for nähtävyydet, pysäköintialueet, bussi-, juna- tai ratikkapysäkki? ==> same as previous

**Question 2:**

- Which icon library/libraries are used? Do we need own symbols for some? #83 solved 
- Where can we find the current symbols used in the mockups ==> added to code

**Styling is needed for:**

- [x] Routes (color, line width, line type)
- [x] Points (icon color, icon size)

Icons for:
- [x] Hiihto
- [x] Luistelu
- [x] Laavut,majat, ruokailu
- [x] Ulkoliikuntapaikat
- [x] Ulkoiluaktiviteetit
- [x] Vesillä retkeily
- [x] Uinti
- [x] Pyöräily
- [x] Nähtävyydet (includes data from Museovirasto and Tampere wfs etc.)
- [x] Pysäköintialue
- [ ] Luonnonsuojelualueet
- [x] Linja-autopysäkki
- [x] Raitiovaunupysäkki
- [x] Juna-asema

**Comment by anniinakovalainen** [comment]
I assigned Riku to this, because you probably will add symbology to points when the filtering is done?

**Comment by SannaJokela** [comment]
@anniinakovalainen ok, so #41 is related

**Comment by SannaJokela** [comment]
@Rikuoja I think this issue is done? The icons and colors are decided. You can close this if or leave it open if you still need this for the coding part. Edited the description.

**Comment by Rikuoja** [comment]
They are decided. They are not implemented. This issue means actually adding the styling to the map.

**Comment by SannaJokela** [comment]
Done for now at least
